### ISSUE TITLE
Input from SRA/GEO

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [krishnanlab/txt2onto#1]
Hi, this tool looks **awesome**! 

Recently we (tagging @Ent22) downloaded +/- 12.000 public h3k27ac samples from GEO/SRA, but we are struggling hard with annotating those, and if I understand correctly txt2onto should help a lot here. I didn't really follow from the methods how I should prepare the text file for these samples. Which text do I use? Do I scrape SRA myself, or does txt2onto come with some util for that?

Thanks!
Maarten (& Okan)

**Comment by nathawkins** [comment]
Hi Maarten,

Thank you for reaching out to us on this matter. As of right now, txt2onto does not include any utilities to download metadata from GEO/SRA or other online databases. This is a functionality that may be included in the future, but a number of packages/tools exist to do this now (e.g., [GEOmetadb](https://www.bioconductor.org/packages/release/bioc/html/GEOmetadb.html)) or as you mentioned, you can scrape SRA. The intention for txt2onto is that a user would curate a corpus of text that they are interesting in annotating for tissues and cell types using our models and run that curated text through our trained models using our utilities. 

For your particular use case, to prepare your text file, you should first download the metadata for your 12,000 samples from GEO/SRA. Then, you need to compile this metadata into a single input file where each line is the metadata for an individual sample. Your input would be a file which is roughly 12,000 lines long with each line corresponding to a single sample. The line of text for each sample will be preprocessed during the prediction step, so this text can contain numerical characters, urls, etc. and our utility will be able to handle it. We have included what an example input text file in our repository [here](https://github.com/krishnanlab/txt2onto/blob/main/data/example_input.txt).  To see how we have formatted our gold standard for the manuscript, see [this file](https://github.com/krishnanlab/txt2onto/blob/main/gold_standard/GoldStandard_Sample-Descriptions.txt). 

An important thing to note is the columns of the prediction dataframe our utility will output corresponds to the rows in your input file. For instance, column 1 of the output dataframe will be the predictions from all of our models (as rows) for that particular line of input text (see the included example output file [here](https://github.com/krishnanlab/txt2onto/blob/main/out/predictions_example_output.txt)). Therefore, it's handy to keep an ID file which keeps track of the sample information for each line of input text (for example, [see this file](https://github.com/krishnanlab/txt2onto/blob/main/gold_standard/GoldStandard_Sample-IDS.txt)).

We hope that this information helps you to utilize our tool for your research! If there is anything further we can clarify, please ask. 

Nat Hawkins

**Comment by Maarten-vd-Sande** [comment]
Thanks for your reply. This all makes sense :smile:
