### ISSUE TITLE
Downgrade overrides to 3.1.0 to import ElmoEmbedder from allennlp.commands.elmo 

### ISSUE THREAD

**Issue by Minghaoy97** [krishnanlab/txt2onto#2]
Hi I tried to implement your work following your instructions, and I found the recent upgraded overrides can fail the import process. It can be solved by downgrading overrides to 3.1.0 in your requirement.txt.

**Comment by nathawkins** [comment]
Thank you for the comment! My apologies for not getting back to this issue sooner. I have included this in a revised `requirements.txt` file. If there is any further issue with this, please let me know.
